### ISSUE TITLE
"on-change" should be "onchange" in README.md

### ISSUE THREAD

**Issue by barryofguilder** [tedconf/ember-ted-select#20]
If I copy the example markup from the README and paste it in my project, my "on change" action does not fire when selecting an option. I set a `debugger` in the TED select component and it's showing `undefined` when checking if the `onchange` action was set. If I update the template to use `onchange` instead of `on-change` (notice the hyphen in the latter), it works.

I'm not sure if that was recently changed in code or if something else weird is happening. I would submit a PR, but I'm not totally sure what's going on, just figured I'd mention it here.

**Comment by barryofguilder** [comment]
Looked through the tests and it looks like it's using `onchange` instead of `on-change`. Here's my pull request: https://github.com/tedconf/ember-ted-select/pull/21

**Comment by brenna** [comment]
Yep, code was changed in a previous release. Docs site but not the readme got updated. PR merged! Appreciate the fix.
