### ISSUE TITLE
Changing 'content' model doesn't reflect in select

### ISSUE THREAD

**Issue by barryofguilder** [tedconf/ember-ted-select#22]
I have two selects rendered on the page. They both share the same backing model, except if an option is selected in one dropdown, then it must be filtered out of the other dropdown to prevent the same option being selected more than once. Here is the computed property for the first dropdown:

``` js
filteredOptions1: Ember.computed('options.[]', 'selectedOption2', function() {
    let selectedOption = this.get('selectedOption2.id');

    return this.get('options').filter((option) => {
      return selectedOption !== option.get('id');
    });
  })
```

My problem is that if I select an option in the second dropdown, the options in the first dropdown don't change in the select tag. If I add a debugger to my computed property, it is being called after selecting the option, and the correct options are being returned from it.

To further test this out, I created a simple dropdown like so and the options reflected correctly in the select tag:

``` hbs
<select>
  {{#each filteredOptions1 as |option|}}
    <option value={{option.id}}>{{option.name}}</option>
  {{/each}}
</select>
```

I'm not sure why they don't update correctly in the ted-select component. Any help would be appreciated. I'll continue to investigate this.

**Comment by barryofguilder** [comment]
Here is an Ember Twiddle reproducing the issue:

https://ember-twiddle.com/25a135fedf0e6064330d9ffc4f985142?openFiles=templates.application.hbs%2Ctemplates.components.ted-select.hbs

**Comment by brenna** [comment]
Hey @barryofguilder,

This appears to be a bug with the `sortedContent` array within the component not updating properly  when a `sortBy` key is not provided.  

I don't have a proper fix for the internals yet, but if sorting is appropriate for your use case, you can hotfix this in your code by adding `sortBy="id"` or similar to your `{{ted-select}}`s:

https://ember-twiddle.com/1199875282d3cad8ce145a2ac0d4a626?openFiles=controllers.application.js%2Ctemplates.components.ted-select.hbs

**Comment by barryofguilder** [comment]
Awesome, that works for me!
