### ISSUE TITLE
`ember install ember-ted-select` is resulting in a generator error.

### ISSUE THREAD

**Issue by bravely** [tedconf/ember-ted-select#24]
``` bash
$ ember install ember-ted-select
Installed packages for tooling via npm.
installing ember-ted-select
The `ember generate <entity-name>` command requires an entity name to be specified. For more details, use `ember help`.
```

I haven't yet been able to find where in the addon any generators are being run, but I figured posting this would possibly help me find it and fix this. It's keeping the addon from working properly at all, as the component is unrecognized by my application afterward.

**Comment by brenna** [comment]
Hi @bravely, can you tell me which version of CLI you're seeing this with?

**Comment by bravely** [comment]
These are my current versions:

``` bash
$ ember -v
ember-cli: 2.4.3
node: 5.9.1
os: darwin x64
```

**Comment by brenna** [comment]
Thanks, I'm able to replicate. Looking into it...

**Comment by brenna** [comment]
Hey @bravely, looks like this is a non-blocking warning masquerading as an error. https://github.com/ember-cli/ember-cli/issues/3831 
I will aim to squash it to prevent future scares but you should still be able to use the addon!

**Comment by bravely** [comment]
When attempting to use the `{{ted-select}}` component after that, it comes off as unrecognized. Did you not encounter that?

**Comment by brenna** [comment]
No, I'm not seeing that on a clean install of CLI 2.4.3. Perhaps try an `rm -rf node_modules`, `npm cache clean` & re-install?
