### ISSUE TITLE
`optionValueKey` should be optional but it isn't; usage with array of strings is impossible

### ISSUE THREAD

**Issue by lolmaus** [tedconf/ember-ted-select#25]
Trying to use `ember-ted-select` with an array of strings. It crashes with:

> Uncaught TypeError: Cannot read property 'toString' of undefined

on this line: 

https://github.com/tedconf/ember-ted-select/blob/v2.0.1/addon/components/ted-select.js#L43

**Comment by brenna** [comment]
`option.get('id')` is what is throwing undefined here.

The default value of `optionValueKey` is `id` so your options objects would have to contain a `id` key, similar to this:

``` js
content = [
  {
    id: 1,
    title: 'apples'
  },
  {
    id: 2,
    title: 'oranges'
  }
]
```

If you don't have an `id` on your passed in objects, you'll need to specify a key with `optionValueKey` so that the select elements have a proper value.

**Comment by lolmaus** [comment]
My `content` is `['foo', 'bar', 'baz']`.

**Comment by brenna** [comment]
`content` needs to be an array of objects, since select element options need both values and labels. I'll update the docs to be more clear on that.

**Comment by lolmaus** [comment]
I find working with an array of strings to be a very basic and highly demanded use case. Obviously, the same string can be used both as a label and value.

I've been making a proper PR for `ember-ted-select` to support working with arrays of strings. Until you've closed this issue. Will continue if you reopen it.

**Comment by brenna** [comment]
This addon is open source but maintained for use in TED's internal apps and that's not a use case we've found necessary. Perhaps a simpler addon or no addon at all would be sufficient for a simple use case like yours.

**Comment by lolmaus** [comment]
But you were chosen for EmberConf...

![image](https://cloud.githubusercontent.com/assets/200884/16993720/28b684f4-4ead-11e6-888c-6362fc651674.png)
