### ISSUE TITLE
support the 'name' attr?

### ISSUE THREAD

**Issue by bgentry** [tedconf/ember-ted-select#27]
Hi there,

Should this component support the `name` attr for the select form field? If so, should the option on the `ted-select` component just be called `name` or something else?

Happy to make a PR if you'd like. Should be pretty straightforward, right?

**Comment by brenna** [comment]
Hello, yes, we could add that if you PR. 

Please make sure to include the following along with the code change:
- [ ] test coverage
- [ ] update the options chart on the README
- [ ] update the docs site (the `tests/dummy` app)

If you need a quicker fix, you can also create your own `components/ted-select.hbs` template in you app, copy in the  [addon's default template](https://github.com/tedconf/ember-ted-select/blob/master/app/templates/components/ted-select.js)    and add the attr there.

**Comment by bgentry** [comment]
#28 should have this covered.

**Comment by brenna** [comment]
Thanks!  available in [v2.1.0](https://github.com/tedconf/ember-ted-select/releases/tag/v2.0.1).
