### ISSUE TITLE
normalizeEntityName is missing in default blueprint

### ISSUE THREAD

**Issue by jbailey4** [tedconf/ember-ted-select#29]
Doing a fresh install I get the following error: `The "ember generate <entity-name>" command requires an entity name to be specified.`

I believe all that needs to be done is to add the missing `normalizeEntityName` method to the default blueprint (`/blueprints/ember-ted-select/index.js`):

`normalizeEntityName: function() {}`

**Comment by brenna** [comment]
Ah sorry bout that. irrc this won't actually prevent the addon from working since nothing is being added in the blueprint, but i'll update so the error gets squashed.

**Comment by brenna** [comment]
fixed in [v2.1.1](https://github.com/tedconf/ember-ted-select/releases/tag/v2.1.1)

**Comment by jbailey4** [comment]
@brenna Awesome thanks.
