### ISSUE TITLE
support disabled

### ISSUE THREAD

**Issue by heygrady** [tedconf/ember-ted-select#7]
This would be helpful in cases where a control should be disabled for some reason.

``` hbs
{{ted-select
  content=myOptions
  disabled=isDisabled}}
```

**Comment by brenna** [comment]
@heygrady good idea. Is this holding up any current implementations?

**Comment by heygrady** [comment]
Not a blocker by any means.

Noticed it here: https://github.com/tedconf/talkstar-frontend/blob/master/app/pods/talks/library/lib/edit-related-talks-find-by-topics/template.hbs#L23
