### ISSUE TITLE
Wrapped records prevent initial selection from working as expected

### ISSUE THREAD

**Issue by heygrady** [tedconf/ember-ted-select#9]
https://github.com/tedconf/ember-ted-select/blob/ember-2/addon/helpers/ted-select-is-equal.js#L4

Using deep equivalency means that it has to literally be the same object. There are cases where the `selected` object is the same record but a different object than what's provided in the list.

For instance, Ember Data likes to wrap a `DS.Model` instance in a `DS.PromiseProxy` when it's returned in a `DS.PromiseArray`. But if your `selected` item was obtained in a different way you'll end up with a mismatch and your item won't be selected. This is a particular problem if you're wrapping your models in a `BufferedProxy`.

``` hbs
{{! may not be selected if selectedComment is not a PromiseProxy and post.comments contains them}}
{{ted-select
  content=post.comments
  selected=selectedComment
  }}
```

It may be useful to compare items using an ID or some other standard "Embery" way of comparing wrapped objects.

**Comment by brenna** [comment]
Deep equivalency was the recommended technique from the Ember deprecation guides: http://emberjs.com/deprecations/v1.x/#toc_ember-select. Not that that's canon, but it makes me less inclined to revise.

Is it a reasonable to say the consumer needs to ensure they're passing in the same type of object or do we try and make it foolproof? 

cc/ @samselikoff @ryanto

**Comment by heygrady** [comment]
I had expected that passing an `optionValueKey` would be used for measuring equivalency (I think selectize does it this way). It's certainly easy to work around.

Something like [this helped](https://github.com/tedconf/talkstar-frontend/blob/searchable-select/app/pods/talks/library/lib/edit-talk-form/component.js#L23-L42):

``` js
  selectedTalkContext: Ember.computed('talk.talkContext', 'talkContexts.[]', function() {
    let talkContext = this.get('talk.talkContext');

    if (!talkContext) {
      return;
    }

    // fix equivalency issue with ModelBufferedProxy and PromiseProxy and Model
    // pick the equivalent value from the list
    // resolves issues of a wrapped record not matching itself
    this.get('talkContexts').any(item => {
      if (item.get('id') === talkContext.get('id')) {
        talkContext = item;
        return true;
      }
      return false;
    });
    return talkContext;
  }),
```

``` hbs
{{ted-select
  content=talkContexts
  selected=selectedTalkContext}}
```

Foolproof probably isn't necessary. This became an issue all over Talkstar after upgrading to the new version of ted-select. Old version was working without issue. Outside of Talkstar the issue will probably come up less because there won't be as many buffered models flying around. This is conceptually similar to a `trackByKey` feature.

If it's not best practice then please close this. Already have a workaround in place on Talkstar.

**Comment by brenna** [comment]
Yeah, I'm honestly not sure what "best practice" is - it's so new that that's still in flux.  Curious to get Sam and Ryan's thoughts on this before closing.

**Comment by brenna** [comment]
IMO, this is a problemo with ember-data and async content being crummy to handle. Closing in the interest of keeping the plugin API straightforward.
